<?php

/**
 * Test class for PathHandler.
 * Generated by PHPUnit on 2012-02-20 at 13:15:43.
 */
class PathHandlerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers FileModule\PathHandler::getRelativePath()
     */
    public function testGetRelativePath()
    {
        $instance = new \FileModule\PathHandler(dirname(dirname(__DIR__)), '/FileModule');
        $path = $instance->getRelativePath('/models');
        $this->assertTrue((bool) strpos($path, 'FileModule/models'));
    }

    /**
     * @covers FileModule\PathHandler::getFullPath()
     */
    public function testGetFullPath()
    {
        $instance = new \FileModule\PathHandler(dirname(__DIR__));

        $path = $instance->getFullPath('/models');
        $this->assertTrue((bool) strpos($path, 'FileModule/models'));
    }

}

?>
